// AUTO-GENERATED by scripts/credits-build.mjs from client/assets/CREDITS.md — DO NOT EDIT BY HAND.
// Regenerate with `npm run credits:build`. The drift check in client/src/credits-data.test.js fails
// CI if this file is out of sync with CREDITS.md. See docs/plans/2026-07-05-1340-credits-screen.md.
export const CREDITS = {
  models: [
    { name: "LowPoly Spaceships", author: "Pedram Ashoori", url: "https://skfb.ly/6pxFX", license: "CC BY 4.0", licenseUrl: "https://creativecommons.org/licenses/by/4.0/", modified: true, requiresAttribution: true },
    { name: "Air & Space Vessel", author: "Raven", url: "https://skfb.ly/otR6F", license: "CC BY 4.0", licenseUrl: "https://creativecommons.org/licenses/by/4.0/", modified: true, requiresAttribution: true },
    { name: "Repair Drone - XYZ Homework (Detailing)", author: "Ivan Potupin", url: "https://skfb.ly/pGPyp", license: "CC BY 4.0", licenseUrl: "https://creativecommons.org/licenses/by/4.0/", modified: true, requiresAttribution: true },
    { name: "machine gun", author: "suvee10", url: "https://skfb.ly/oHLZB", license: "CC BY 4.0", licenseUrl: "https://creativecommons.org/licenses/by/4.0/", modified: true, requiresAttribution: true },
    { name: "Freighter - Spaceship", author: "Felipe Augusto Vera", url: "https://skfb.ly/oPRwV", license: "CC BY 4.0", licenseUrl: "https://creativecommons.org/licenses/by/4.0/", modified: true, requiresAttribution: true },
    { name: "Metal box", author: "District24", url: "https://skfb.ly/JwFQ", license: "CC BY 4.0", licenseUrl: "https://creativecommons.org/licenses/by/4.0/", modified: true, requiresAttribution: true },
    { name: "Low Poly space station.", author: "MisterH", url: "https://skfb.ly/ozESS", license: "CC BY 4.0", licenseUrl: "https://creativecommons.org/licenses/by/4.0/", modified: true, requiresAttribution: true },
  ],
  sounds: [
    { name: "kinetic gun SFX", author: "serutonin-deprivd", url: "https://freesound.org/s/855652/", license: "CC0 1.0", licenseUrl: null, modified: false, requiresAttribution: false },
    { name: "rocket launch SFX", author: "smokey9977", url: "https://freesound.org/s/569563/", license: "CC0 1.0", licenseUrl: null, modified: false, requiresAttribution: false },
    { name: "Heavy cannon SFX", author: "Freesound (CC0 filter)", url: null, license: "CC0 1.0", licenseUrl: null, modified: false, requiresAttribution: false },
    { name: "kinetic hit on player ship", author: "Freesound (CC0 filter)", url: null, license: "CC0 1.0", licenseUrl: null, modified: false, requiresAttribution: false },
    { name: "medium/large ship explosion", author: "Freesound (CC0 filter)", url: null, license: "CC0 1.0", licenseUrl: null, modified: false, requiresAttribution: false },
    { name: "rocket + small ship explosion, from blast.flac", author: "Freesound (CC0 filter)", url: null, license: "CC0 1.0", licenseUrl: null, modified: false, requiresAttribution: false },
    { name: "hangar background loop", author: "Freesound (CC0 filter)", url: null, license: "CC0 1.0", licenseUrl: null, modified: false, requiresAttribution: false },
    { name: "combat background loop", author: "Freesound (CC0 filter)", url: null, license: "CC0 1.0", licenseUrl: null, modified: false, requiresAttribution: false },
    { name: "combat background track — \"Energetic Synthwave\"", author: "ed-musicproductions", url: "https://pixabay.com/music/synthwave-energetic-synthwave-412360/", license: "Pixabay Content License", licenseUrl: null, modified: false, requiresAttribution: false },
  ],
};
